name = "NthTropicalNevanlinna"
version = "0.1.0"
defaultTargets = ["NthTropicalNevanlinna"]

[[lean_lib]]
name = "NthTropicalNevanlinna"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "887d94632e78e6e41701cf57c3e7206c6c2b1e5b"
